### ISSUE TITLE
No micropython.cmake file

### ISSUE THREAD

**Issue by MATTYGILO** [dmazzella/ucrypto#3] opened 2022-05-04 08:21 UTC
This repo has no micropython.cmake file, so how can we compile?

**Comment by MATTYGILO** [comment] 2022-05-04 12:18
Will this micropython.cmake file work?
```
add_library(usermod_ufastecdsa INTERFACE)

target_sources(usermod_ufastecdsa INTERFACE
    ${CMAKE_CURRENT_LIST_DIR}/moducrypto.c
)

target_include_directories(usermod_ufastecdsa INTERFACE
    ${CMAKE_CURRENT_LIST_DIR}
)

target_link_libraries(usermod INTERFACE usermod_ufastecdsa)
```

**Comment by dmazzella** [comment] 2022-05-04 12:22
Try with last push

**Comment by dmazzella** [comment] 2022-05-04 12:27
duplicate of #2

**Closed as completed by dmazzella** 2022-05-04 12:27 UTC
Labels: duplicate
